package integration

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/hanwen/go-fuse/v2/fuse"
	"github.com/jra3/linear-fuse/internal/config"
	"github.com/jra3/linear-fuse/internal/fs"
)

// TestGeneratedReadmeMatchesBehavior ties the mounted README.md (generated by
// internal/fs.generateReadme) to actual filesystem behavior, so the doc can't
// silently drift from the code again. It guards the specific bug the code review
// surfaced: the README claimed _create reads "return empty" while every _create
// node actually returns EACCES.
func TestGeneratedReadmeMatchesBehavior(t *testing.T) {
	data, err := os.ReadFile(filepath.Join(mountPoint, "README.md"))
	if err != nil {
		t.Fatalf("read README.md: %v", err)
	}
	readme := string(data)

	// The old, inaccurate claim must not reappear.
	if strings.Contains(readme, "returns empty (size 0)") {
		t.Error("README claims _create reads return empty, but _create nodes return EACCES")
	}

	// It should document the surfaces this branch added so agents learn about them.
	// "recent created updates" guards the updates trio: updates/ directories were
	// the last create surface without .error/.last, which made the README's global
	// "every writable directory has a .error" claim false there.
	// "relations, updates" pins updates' membership in the .last surface list;
	// "creates one item" pins the per-write-cycle semantics (each write to
	// _create creates another item — the old node-level buffers silently
	// swallowed the second write, so nothing documented it).
	// "targeted catalog refresh" pins the stale-catalog self-healing doc (#246):
	// a local name→ID miss refreshes the catalog once and retries before .error.
	// "outcome: failed" pins the .last outcome-log contract (#370): a failed
	// create appends a countable failure entry rather than .error collapsing to
	// only the last failure of a batch.
	for _, want := range []string{".last", "issue.meta", "initiative.meta", "recent/", "recent created updates", "relations, updates", "creates one item", "targeted catalog refresh", "outcome: failed"} {
		if !strings.Contains(readme, want) {
			t.Errorf("README does not mention %q", want)
		}
	}

	// The project/initiative external-link surface (#249): the README must teach
	// the links/ directory and its "URL [label]" write contract, and the *.link
	// files must really be read-only (a documented write-only/read-only surface
	// that lies is the exact failure this test exists to prevent).
	for _, want := range []string{"links/", ".link", "URL [label]"} {
		if !strings.Contains(readme, want) {
			t.Errorf("README does not mention %q (project/initiative links surface)", want)
		}
	}

	// The meta split moved server fields out of the editable files. The README's
	// frontmatter templates must not document them as editable-file fields, or an
	// agent will look for/edit fields that no longer live there (the exact "the
	// generated README silently lies" failure this test exists to prevent). The
	// initiative template used to show slug:/targetDate:/owner: inside initiative.md.
	for _, leak := range []string{"slug: 77d439e363bb", "targetDate:"} {
		if strings.Contains(readme, leak) {
			t.Errorf("README documents %q as an editable-file field, but it moved to .meta", leak)
		}
	}

	// The collection meta split: every collection item {base}.md is documented
	// with a read-only {base}.meta sidecar, and comment .md files are the pure
	// body. The README's structure map must teach both.
	for _, want := range []string{"{id}.meta", "{slug}.meta", "{name}.meta", "no frontmatter", "*.meta sidecar"} {
		if !strings.Contains(readme, want) {
			t.Errorf("README does not mention %q (collection meta split)", want)
		}
	}
	// And the documented surfaces must really behave that way: a fixture doc's
	// .meta exists, reads, and rejects writes; the comment .md has no frontmatter.
	if entries, err := os.ReadDir(docsPath(testTeamKey, "TST-1")); err == nil {
		for _, e := range entries {
			if isControlFile(e.Name()) || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			metaPath := docFilePath(testTeamKey, "TST-1", strings.TrimSuffix(e.Name(), ".md")+".meta")
			if _, err := os.ReadFile(metaPath); err != nil {
				t.Errorf("README documents doc .meta sidecars but %s is unreadable: %v", metaPath, err)
			}
			if err := os.WriteFile(metaPath, []byte("x"), 0644); err == nil {
				t.Errorf("README documents %s as read-only but it accepted a write", metaPath)
			}
			break
		}
	}
	if entries, err := os.ReadDir(commentsPath(testTeamKey, "TST-1")); err == nil {
		for _, e := range entries {
			if isControlFile(e.Name()) || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			content, err := os.ReadFile(commentFilePath(testTeamKey, "TST-1", e.Name()))
			if err == nil && strings.HasPrefix(string(content), "---") {
				t.Errorf("README documents comment .md as frontmatter-free, but %s carries frontmatter", e.Name())
			}
			break
		}
	}

	// Spot-check the documented _create read behavior against the real node:
	// reading issues/_create must fail (write-only), matching the README.
	if _, err := os.ReadFile(issuesPath(testTeamKey) + "/_create"); err == nil {
		t.Error("issues/_create is readable, but README documents it as write-only")
	}

	// The create tail unified the failure model and closed the .last gap: the
	// README must document EAGAIN/ENOENT/EMSGSIZE alongside EINVAL/EIO, and must
	// not resurrect the "attachments and relations don't report to .last" carve-out.
	for _, want := range []string{"EAGAIN", "ENOENT", "EMSGSIZE"} {
		if !strings.Contains(readme, want) {
			t.Errorf("README failure model does not mention %q", want)
		}
	}
	if strings.Contains(readme, "instead surface the result") {
		t.Error("README carves attachments/relations out of .last, but every create surface reports to .last now")
	}

	// #5: project/initiative bodies map to the long content field, not the ≤255
	// description; the README must not tell writers the body is the description
	// (which silently rejected any real write-up), and must place description in
	// the read-only .meta.
	if !strings.Contains(readme, "the body maps to the long content") {
		t.Error("README does not document that project/initiative bodies map to content")
	}
	if strings.Contains(readme, "the body maps to the description)") {
		t.Error("README still claims a project/initiative body maps to the ≤255 description field (#5)")
	}

	// Project labels (#130): the README must teach the catalog surface and the
	// assignment rules ("one child" pins group exclusivity; "retired" pins the
	// lifecycle; the reference-files line must point at the catalog).
	for _, want := range []string{"project-labels.md", "one child", "retired", "Validated project fields"} {
		if !strings.Contains(readme, want) {
			t.Errorf("README does not mention %q", want)
		}
	}
	// And the documented surface must really exist, read-only, with the
	// group marker the rules refer to.
	catalog, err := os.ReadFile(filepath.Join(mountPoint, "project-labels.md"))
	if err != nil {
		t.Fatalf("README documents project-labels.md but it is unreadable: %v", err)
	}
	if !strings.Contains(string(catalog), "group") {
		t.Error("project-labels.md does not carry the group marker the README describes")
	}
	if info, err := os.Stat(filepath.Join(mountPoint, "project-labels.md")); err == nil && info.Mode().Perm() != 0444 {
		t.Errorf("project-labels.md mode = %v, want 0444 (README: read-only)", info.Mode().Perm())
	}

	// #366: the agent self-reporting protocol is opt-in (USER_FEEDBACK). The
	// suite mounts without it, so the served README must not carry it — a
	// default mount never tells an agent to file issues on this repo. The
	// flag-on shape is pinned by internal/fs.TestGenerateReadmeFeedbackFlag.
	for _, leak := range []string{"agent_feedback_protocol", "dx-friction", "gh issue create"} {
		if strings.Contains(readme, leak) {
			t.Errorf("README carries %q without USER_FEEDBACK set (the protocol must be opt-in)", leak)
		}
	}
}

// TestUserFeedbackReadmeThroughMount is the flag-on half of #366's acceptance:
// with config.UserFeedback set, the README served through a real mount carries
// the self-reporting protocol. It mounts its own filesystem because the suite's
// shared mount deliberately runs with the flag off (see above). No store is
// needed — the README is a pure render.
func TestUserFeedbackReadmeThroughMount(t *testing.T) {
	mnt, err := os.MkdirTemp("", "linearfs-test-feedback-*")
	if err != nil {
		t.Fatalf("create mount point: %v", err)
	}
	lfs, err := fs.NewLinearFS(&config.Config{APIKey: "feedback-mode-key", UserFeedback: true}, false)
	if err != nil {
		os.RemoveAll(mnt)
		t.Fatalf("create linearfs: %v", err)
	}
	srv, err := fs.MountFS(mnt, lfs, false)
	if err != nil {
		lfs.Close()
		os.RemoveAll(mnt)
		t.Fatalf("mount filesystem: %v", err)
	}
	t.Cleanup(func() {
		unmounted := unmountBestEffort(t, srv, mnt)
		lfs.Close()
		// Only walk the directory once it is really a plain directory again.
		// RemoveAll on a live mount readdirs *through* the filesystem, and this
		// FS deliberately has no store behind it, so a lookup there would panic
		// the whole test binary (go-fuse does not recover in the request path).
		if !unmounted {
			t.Logf("leaving %s in place: still mounted", mnt)
			return
		}
		os.RemoveAll(mnt)
	})

	data, err := os.ReadFile(filepath.Join(mnt, "README.md"))
	if err != nil {
		t.Fatalf("read README.md: %v", err)
	}
	readme := string(data)

	// The protocol must be there, actionable: the label, the create command, the
	// dedup search, and the receipt the human sees.
	for _, want := range []string{
		"<agent_feedback_protocol>",
		"dx-friction",
		"gh issue create --repo jra3/linear-fuse",
		"gh issue list --repo jra3/linear-fuse --search",
		"filed linear-fuse bug #N",
	} {
		if !strings.Contains(readme, want) {
			t.Errorf("USER_FEEDBACK README does not mention %q", want)
		}
	}
	// And it is append-only: the normal doc is still fully there.
	for _, want := range []string{"<directory_structure>", "</claude_code_instructions>"} {
		if !strings.Contains(readme, want) {
			t.Errorf("USER_FEEDBACK README lost %q; the protocol must only append", want)
		}
	}
}

// unmountBestEffort tears down a test's own mount the way the suite's cleanup()
// does: unmount, and on EBUSY (a straggling fd) retry once, then lazy-detach so
// the kernel completes the unmount when the last fd closes. It reports whether
// the path is a plain directory again — a caller must not walk or remove it
// otherwise, since that would issue FUSE requests against a torn-down server.
func unmountBestEffort(t *testing.T, srv *fuse.Server, mnt string) bool {
	t.Helper()
	err := srv.Unmount()
	if err == nil {
		return true
	}
	time.Sleep(200 * time.Millisecond)
	if err := srv.Unmount(); err == nil {
		return true
	}
	// An unprivileged umount2 is not permitted on FUSE; the setuid helper
	// lazy-detaches instead (darwin has no fusermount3).
	cmd := exec.Command("fusermount3", "-uz", mnt)
	if runtime.GOOS == "darwin" {
		cmd = exec.Command("umount", "-f", mnt)
	}
	if out, lerr := cmd.CombinedOutput(); lerr != nil {
		t.Logf("Warning: unmount %s failed (%v), lazy detach failed too (%v: %s); clean it manually", mnt, err, lerr, out)
		return false
	}
	// Lazy: the mount goes away when the last fd closes, which may be after
	// this returns, so the directory is not safe to walk yet.
	t.Logf("Note: %s was busy at cleanup; lazy-detached", mnt)
	return false
}
