package integration

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGeneratedReadmeMatchesBehavior ties the mounted README.md (generated by
// internal/fs.generateReadme) to actual filesystem behavior, so the doc can't
// silently drift from the code again. It guards the specific bug the code review
// surfaced: the README claimed _create reads "return empty" while every _create
// node actually returns EACCES.
func TestGeneratedReadmeMatchesBehavior(t *testing.T) {
	data, err := os.ReadFile(filepath.Join(mountPoint, "README.md"))
	if err != nil {
		t.Fatalf("read README.md: %v", err)
	}
	readme := string(data)

	// The old, inaccurate claim must not reappear.
	if strings.Contains(readme, "returns empty (size 0)") {
		t.Error("README claims _create reads return empty, but _create nodes return EACCES")
	}

	// It should document the surfaces this branch added so agents learn about them.
	// "recent created updates" guards the updates trio: updates/ directories were
	// the last create surface without .error/.last, which made the README's global
	// "every writable directory has a .error" claim false there.
	for _, want := range []string{".last", "issue.meta", "initiative.meta", "recent/", "recent created updates"} {
		if !strings.Contains(readme, want) {
			t.Errorf("README does not mention %q", want)
		}
	}

	// The meta split moved server fields out of the editable files. The README's
	// frontmatter templates must not document them as editable-file fields, or an
	// agent will look for/edit fields that no longer live there (the exact "the
	// generated README silently lies" failure this test exists to prevent). The
	// initiative template used to show slug:/targetDate:/owner: inside initiative.md.
	for _, leak := range []string{"slug: 77d439e363bb", "targetDate:"} {
		if strings.Contains(readme, leak) {
			t.Errorf("README documents %q as an editable-file field, but it moved to .meta", leak)
		}
	}

	// Spot-check the documented _create read behavior against the real node:
	// reading issues/_create must fail (write-only), matching the README.
	if _, err := os.ReadFile(issuesPath(testTeamKey) + "/_create"); err == nil {
		t.Error("issues/_create is readable, but README documents it as write-only")
	}

	// The create tail unified the failure model and closed the .last gap: the
	// README must document EAGAIN/ENOENT alongside EINVAL/EIO, and must not
	// resurrect the "attachments and relations don't report to .last" carve-out.
	for _, want := range []string{"EAGAIN", "ENOENT"} {
		if !strings.Contains(readme, want) {
			t.Errorf("README failure model does not mention %q", want)
		}
	}
	if strings.Contains(readme, "instead surface the result") {
		t.Error("README carves attachments/relations out of .last, but every create surface reports to .last now")
	}
}
