package integration

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGeneratedReadmeMatchesBehavior ties the mounted README.md (generated by
// internal/fs.generateReadme) to actual filesystem behavior, so the doc can't
// silently drift from the code again. It guards the specific bug the code review
// surfaced: the README claimed _create reads "return empty" while every _create
// node actually returns EACCES.
func TestGeneratedReadmeMatchesBehavior(t *testing.T) {
	data, err := os.ReadFile(filepath.Join(mountPoint, "README.md"))
	if err != nil {
		t.Fatalf("read README.md: %v", err)
	}
	readme := string(data)

	// The old, inaccurate claim must not reappear.
	if strings.Contains(readme, "returns empty (size 0)") {
		t.Error("README claims _create reads return empty, but _create nodes return EACCES")
	}

	// It should document the surfaces this branch added so agents learn about them.
	for _, want := range []string{".last", "issue.meta", "recent/"} {
		if !strings.Contains(readme, want) {
			t.Errorf("README does not mention %q", want)
		}
	}

	// Spot-check the documented _create read behavior against the real node:
	// reading issues/_create must fail (write-only), matching the README.
	if _, err := os.ReadFile(issuesPath(testTeamKey) + "/_create"); err == nil {
		t.Error("issues/_create is readable, but README documents it as write-only")
	}
}
