// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Issue struct {
	ID            string          `json:"id"`
	Identifier    string          `json:"identifier"`
	TeamID        string          `json:"team_id"`
	Title         string          `json:"title"`
	Description   sql.NullString  `json:"description"`
	StateID       sql.NullString  `json:"state_id"`
	StateName     sql.NullString  `json:"state_name"`
	StateType     sql.NullString  `json:"state_type"`
	AssigneeID    sql.NullString  `json:"assignee_id"`
	AssigneeEmail sql.NullString  `json:"assignee_email"`
	Priority      sql.NullInt64   `json:"priority"`
	ProjectID     sql.NullString  `json:"project_id"`
	ProjectName   sql.NullString  `json:"project_name"`
	CycleID       sql.NullString  `json:"cycle_id"`
	CycleName     sql.NullString  `json:"cycle_name"`
	ParentID      sql.NullString  `json:"parent_id"`
	DueDate       sql.NullString  `json:"due_date"`
	Estimate      sql.NullFloat64 `json:"estimate"`
	Url           sql.NullString  `json:"url"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	SyncedAt      time.Time       `json:"synced_at"`
	Data          json.RawMessage `json:"data"`
}

type IssuesFt struct {
	Identifier  string `json:"identifier"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type SyncMetum struct {
	TeamID             string        `json:"team_id"`
	LastSyncedAt       time.Time     `json:"last_synced_at"`
	LastIssueUpdatedAt sql.NullTime  `json:"last_issue_updated_at"`
	IssueCount         sql.NullInt64 `json:"issue_count"`
}

type Team struct {
	ID        string         `json:"id"`
	Key       string         `json:"key"`
	Name      string         `json:"name"`
	Icon      sql.NullString `json:"icon"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	SyncedAt  time.Time      `json:"synced_at"`
}
